version: "3"

services:
  loki:
    image: grafana/loki:2.8.0
    container_name: loki
    ports:
      - "3100:3100"  # Loki API port
    networks:
      - monitoring
    volumes:
      - ./loki-config.yml:/etc/loki/loki-config.yml

  app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    networks:
      - app-network
      - monitoring   # Ensure app is also on monitoring network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx-reverse-proxy
    ports:
      - "8888:80"
    depends_on:
      - app
    networks:
      - app-network
      - monitoring   # Ensure nginx is also on monitoring network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - app-network
      - monitoring   # Ensure prometheus is on both networks

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3030:3000"  # Changed Grafana port to 3030
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - app-network
      - monitoring   # Ensure grafana is on monitoring network

  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    ports:
      - "8080:8080"
    networks:
      - app-network
      - monitoring

  promtail:
    image: grafana/promtail:2.8.0
    container_name: promtail
    volumes:
      - /var/log:/var/log  # Collect log files
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml
    networks:
      - monitoring

networks:
  app-network:
    driver: bridge
  monitoring:
    driver: bridge

volumes:
  grafana-data:
