version: "3"

services:
  app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    networks:
      - app-network
      - monitoring   # Ensure app is also on monitoring network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx-reverse-proxy
    ports:
      - "8888:80"
    depends_on:
      - app
    networks:
      - app-network
      - monitoring   # Ensure nginx is also on monitoring network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - app-network
      - monitoring   # Ensure prometheus is on both networks

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3030:3000"  # Changed Grafana port to 3030
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - app-network
      - monitoring   # Ensure grafana is on monitoring network

networks:
  app-network:
    driver: bridge
  monitoring:
    driver: bridge

volumes:
  grafana-data:
