auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

ingester:
  wal:
    enabled: true
    dir: /tmp/wal

storage_config:
  boltdb_shipper:
    active_index_directory: /tmp/loki/index
    cache_location: /tmp/loki/cache
  filesystem:
    directory: /tmp/loki/chunks

schema_config:
  configs:
    - from: 2022-01-01
      store: boltdb
      object_store: filesystem
      schema: v11
      index:
        prefix: loki_index_
        period: 168h
