global:
  scrape_interval: 5s  # Adjust as needed

scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']

  - job_name: 'flask-app'
    static_configs:
      - targets: ['flask-app:5000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
