global:
  scrape_interval: 5s  # Adjust as needed

scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']  # Nginx service is accessible by name on the app-network

  - job_name: 'flask-app'
    static_configs:
      - targets: ['flask-app:5000']  # Flask app service is accessible by name on the app-network
